export default {
  continents: [
    {
      name:'África',
      original: 'Africa',
      id: '1'
    },
    {
      name:'América',
      original: 'America',
      id: '2'
    },
    {
      name:'Asia',
      original: 'Asia',
      id: '3'
    },
    {
      name:'Atlántico',
      original: 'Atlantic',
      id: '4'
    },
    {
      name:'Australia/Oceanía',
      original: 'Australia',
      id: '5'
    },
    {
      name:'Europa',
      original: 'Europe',
      id: '6'
    },
    {
      name:'Pacífico',
      original: 'Pacific',
      id: '7'
    }
  ],
  cities_america: [
    {name:'Adak, Alaska', original:'Adak'},
    {name:'Anchorage, Alaska', original:'Anchorage'},
    {name:'Araguaína, Brasil', original:'Araguaina'},
    {name:'Buenos Aires, Argentina', original:'Buenos_Aires'},
    {name:'Asunción, Paraguay', original:'Asuncion'},
    {name:'Atikokan, Canadá', original:'Atikokan'},
    {name:'Bahía, Brasil', original:'Bahia'},
    {name:'Bahía Banderas, México', original:'Bahia_Banderas'},
    {name:'Barbados, Caribe', original:'Barbados'},
    {name:'Belém, Brasil', original:'Belem'},
    {name:'Belize, Belize', original:'Belize'},
    {name:'Blanc Sablon, Canadá', original:'Blanc-Sablon'},
    {name:'Boa Vista, Brasil', original:'Boa_Vista'},
    {name:'Bogotá, Colombia', original:'Bogota'},
    {name:'Boise, Idaho', original:'Boise'},
    {name:'Cambridge Bay, Canadá', original:'Cambridge_Bay'},
    {name:'Campo Grande, Brasil', original:'Campo_Grande'},
    {name:'Cancún, México', original:'Cancun'},
    {name:'Caracas, Venezuela', original:'Caracas'},
    {name:'Cayenne, Guayana Francesa', original:'Cayenne'},
    {name:'Chicago, Illinois', original:'Chicago'},
    {name:'Chihuahua, México', original:'Chihuahua'},
    {name:'Costa Rica', original:'Costa_Rica'},
    {name:'Creston, Canadá', original:'Creston'},
    {name:'Cuiaba, Brasil', original:'Cuiaba'},
    {name:'Curacao, Caribe', original:'Curacao'},
    {name:'Danmarkshavn, Groenlandia', original:'Danmarkshavn'},
    {name:'Dawson, Canadá', original:'Dawson'},
    {name:'Dawson Creek, Canadá', original:'Dawson_Creek'},
    {name:'Denver, Estados Unidos', original:'Denver'},
    {name:'Detroit, Estados Unidos', original:'Detroit'},
    {name:'Edmonton, Canadá', original:'Edmonton'},
    {name:'Eirunepe, Brasil', original:'Eirunepe'},
    {name:'El Salvador', original:'El_Salvador'},
    {name:'Fort Nelson, Canadá', original:'Fort_Nelson'},
    {name:'Fortaleza, Brasil', original:'Fortaleza'},
    {name:'Glace Bay, Canadá', original:'Glace_Bay'},
    {name:'Goose Bay, Canadá', original:'Goose_Bay'},
    {name:'Grand Turk, Islas Turcas y Caicos', original:'Grand_Turk'},
    {name:'Ciudad de Guatemala, Guatemala', original:'Guatemala'},
    {name:'Guayaquil, Ecuador', original:'Guayaquil'},
    {name:'Guyana', original:'Guyana'},
    {name:'Halifax, Canadá', original:'Halifax'},
    {name:'La Habana, Cuba', original:'Havana'},
    {name:'Hermosillo, México', original:'Hermosillo'},
    {name:'Indianápolis, Indiana', original:'Indiana/Indianapolis'},
    {name:'Knox, Indiana', original:'Indiana/Knox'},
    {name:'Marengo, Indiana', original:'Indiana/Marengo'},
    {name:'Petersburg, Indiana', original:'Indiana/Petersburg'},
    {name:'Tell City, Indiana', original:'Indiana/Tell_City'},
    {name:'Vevay, Indiana', original:'Indiana/Vevay'},
    {name:'Vincennes, Indiana', original:'Indiana/Vincennes'},
    {name:'Winamac, Indiana', original:'Indiana/Winamac'},
    {name:'Inuvik, Canadá', original:'Inuvik'},
    {name:'Iqaluit, Canadá', original:'Iqaluit'},
    {name:'Jamaica, Caribe', original:'Jamaica'},
    {name:'Juneau, Alaska', original:'Juneau'},
    {name:'Louisville, Estados Unidos', original:'KentuckyLouisville'},
    {name:'Monticello, Estados Unidos', original:'KentuckyMonticello'},
    {name:'La Paz, Bolivia', original:'La_Paz'},
    {name:'Lima, Perú', original:'Lima'},
    {name:'Los Ángeles, Estados Unidos', original:'Los_Angeles'},
    {name:'Maceio, Brasil', original:'Maceio'},
    {name:'Managua, Nicaragua', original:'Managua'},
    {name:'Manaus, Brasil', original:'Manaus'},
    {name:'Martinique, Caribe', original:'Martinique'},
    {name:'Matamoros, México', original:'Matamoros'},
    {name:'Mazatlan, México', original:'Mazatlan'},
    {name:'Menominee, Estados Unidos', original:'Menominee'},
    {name:'Mérida, México', original:'Merida'},
    {name:'Metlakatla, Alaska', original:'Metlakatla'},
    {name:'Ciudad de México, México', original:'Mexico_City'},
    {name:'Miquelon, Canadá', original:'Miquelon'},
    {name:'Moncton, Canadá', original:'Moncton'},
    {name:'Monterrey, México', original:'Monterrey'},
    {name:'Montevideo, Uruguay', original:'Montevideo'},
    {name:'Nassau, Bahamas', original:'Nassau'},
    {name:'New York, Estados Unidos', original:'New_York'},
    {name:'Nipigon, Canadá', original:'Nipigon'},
    {name:'Nome, Alaska', original:'Nome'},
    {name:'Noronha, Brasil', original:'Noronha'},
    {name:'Beulah, Dakota del Norte', original:'North_Dakota/Beulah'},
    {name:'Center, Dakota del Norte', original:'North_Dakota/Center'},
    {name:'New Salem, Dakota del Norte', original:'North_Dakota/New_Salem'},
    {name:'Nuuk, Groenlandia', original:'Nuuk'},
    {name:'Ojinaga, México', original:'Ojinaga'},
    {name:'Panamá', original:'Panama'},
    {name:'Pangnirtung, Canadá', original:'Pangnirtung'},
    {name:'Paramaribo, Surinam', original:'Paramaribo'},
    {name:'Phoenix, Estados Unidos', original:'Phoenix'},
    {name:'Puerto Príncipe, Haití', original:'Port-au-Prince'},
    {name:'Puerto España, Trinidad y Tobago', original:'Port_of_Spain'},
    {name:'Porto Velho, Brasil', original:'Porto_Velho'},
    {name:'Puerto Rico', original:'Puerto_Rico'},
    {name:'Punta Arenas, Chile', original:'Punta_Arenas'},
    {name:'Rainy River, Canadá', original:'Rainy_River'},
    {name:'Rankin Inlet, Canadá', original:'Rankin_Inlet'},
    {name:'Recife, Brasil', original:'Recife'},
    {name:'Regina, Canadá', original:'Regina'},
    {name:'Resolute, Canadá', original:'Resolute'},
    {name:'Río Branco, Uruguay', original:'Rio_Branco'},
    {name:'Santarem, Brasil', original:'Santarem'},
    {name:'Santiago, Chile', original:'Santiago'},
    {name:'Santo Domingo, República Dominicana', original:'Santo_Domingo'},
    {name:'Sao Paulo, Brasil', original:'Sao_Paulo'},
    {name:'Scoresbysund/Ittoqqortoormiit, Groenlandia', original:'Scoresbysund'},
    {name:'Sitka, Alaska', original:'Sitka'},
    {name:'Saint John, Antigua y Barbuda', original:'St_Johns'},
    {name:'Swift Current, Canadá', original:'Swift_Current'},
    {name:'Tegucigalpa, Honduras', original:'Tegucigalpa'},
    {name:'Thunder Bay, Canadá', original:'Thunder_Bay'},
    {name:'Tijuana, México', original:'Tijuana'},
    {name:'Toronto, Canadá', original:'Toronto'},
    {name:'Vancouver, Canadá', original:'Vancouver'},
    {name:'Whitehorse, Canadá', original:'Whitehorse'},
    {name:'Winnipeg, Canadá', original:'Winnipeg'},
    {name:'Yakutat, Alaska', original:'Yakutat'},
    {name:'Yellowknife, Canadá', original:'Yellowknife'}
  ],
  cities_europa: [
    {name:'Ámsterdam, Holanda', original:'Amsterdam'},
    {name:'Andorra', original:'Andorra'},
    {name:'Astrakhan, Rusia', original:'Astrakhan'},
    {name:'Athens, Grecia', original:'Athens'},
    {name:'Belgrade, Serbia', original:'Belgrade'},
    {name:'Berlín, Alemania', original:'Berlin'},
    {name:'Brussels, Bélgica', original:'Brussels'},
    {name:'Bucharest, Rumania', original:'Bucharest'},
    {name:'Budapest, Hungría', original:'Budapest'},
    {name:'Chisinau, Moldavia', original:'Chisinau'},
    {name:'Copenhagen, Dinamarca', original:'Copenhagen'},
    {name:'Dublin, Irlanda', original:'Dublin'},
    {name:'Gibraltar', original:'Gibraltar'},
    {name:'Helsinki, Finlandia', original:'Helsinki'},
    {name:'Estambul/Istanbul, Turquía', original:'Istanbul'},
    {name:'Kaliningrado/Kaliningrad, Rusia', original:'Kaliningrad'},
    {name:'Kiev, Ucrania', original:'Kiev'},
    {name:'Kirov, Rusia', original:'Kirov'},
    {name:'Lisboa, Portugal', original:'Lisbon'},
    {name:'Londres/London, Inglaterra', original:'London'},
    {name:'Luxembourg', original:'Luxembourg'},
    {name:'Madrid, España', original:'Madrid'},
    {name:'Malta', original:'Malta'},
    {name:'Minsk, Bielorrusia', original:'Minsk'},
    {name:'Mónaco', original:'Monaco'},
    {name:'Moscow, Rusia', original:'Moscow'},
    {name:'Oslo, Noruega', original:'Oslo'},
    {name:'París, Francia', original:'Paris'},
    {name:'Praga, República Checa', original:'Prague'},
    {name:'Riga, Letonia', original:'Riga'},
    {name:'Roma, Italia', original:'Rome'},
    {name:'Samara, Rusia', original:'Samara'},
    {name:'Sarátov, Rusia', original:'Saratov'},
    {name:'Simferopol, Rusia', original:'Simferopol'},
    {name:'Sofía, Bulgaria', original:'Sofia'},
    {name:'Estocolmo/Stockholm, Suecia', original:'Stockholm'},
    {name:'Tallinn, Estonia', original:'Tallinn'},
    {name:'Tirane, Albania', original:'Tirane'},
    {name:'Ulyanovsk, Rusia', original:'Ulyanovsk'},
    {name:'Úzhgorod, Ucrania', original:'Uzhgorod'},
    {name:'Vienna, Austria', original:'Vienna'},
    {name:'Vilnius, Lituania', original:'Vilnius'},
    {name:'Volgogrado, Rusia', original:'Volgograd'},
    {name:'Varsovia/Warsaw, Polonia', original:'Warsaw'},
    {name:'Zaporozhye, Ucrania', original:'Zaporozhye'},
    {name:'Zúrich, Suiza', original:'Zurich'}
  ],
  cities_africa: [
    {name:'Abidjan, Costa de Marfil', original:'Abidjan'},
    {name:'Accra, Ghana', original:'Accra'},
    {name:'Algiers, Algeria', original:'Algiers'},
    {name:'Bissau, Guinea-Bisáu', original:'Bissau'},
    {name:'El Cairo, Egipto', original:'Cairo'},
    {name:'Casablanca, Marruecos', original:'Casablanca'},
    {name:'Ceuta, España', original:'Ceuta'},
    {name:'El Aaiún, España', original:'El_Aaiun'},
    {name:'Johannesburg, Sudáfrica', original:'Johannesburg'},
    {name:'Juba, Sudán del Sur', original:'Juba'},
    {name:'Khartoum, Sudán', original:'Khartoum'},
    {name:'Lagos, Nigeria', original:'Lagos'},
    {name:'Maputo, Mozambique', original:'Maputo'},
    {name:'Monrovia, Liberia', original:'Monrovia'},
    {name:'Nairobi, Kenia', original:'Nairobi'},
    {name:'Ndjamena, Chad', original:'Ndjamena'},
    {name:'Santo Tomé y Príncipe', original:'Sao_Tome'},
    {name:'Tripoli, Libia', original:'Tripoli'},
    {name:'Túnez', original:'Tunis'},
    {name:'Windhoek, Namibia', original:'Windhoek'}
  ],
  cities_asia: [
    {name:'Almatý, Kazajistán', original:'Almaty'},
    {name:'Amán/Amman, Jordania', original:'Amman'},
    {name:'Anadyr, Rusia', original:'Anadyr'},
    {name:'Aqtau, Kazajistán', original:'Aqtau'},
    {name:'Aqtobe, Kazajistán', original:'Aqtobe'},
    {name:'Ashgabat, Turkmenistán', original:'Ashgabat'},
    {name:'Atyrau, Kazajistán', original:'Atyrau'},
    {name:'Baghdad, Irak', original:'Baghdad'},
    {name:'Bakú, Azerbaiyán', original:'Baku'},
    {name:'Bangkok, Tailandia', original:'Bangkok'},
    {name:'Barnaul, Rusia', original:'Barnaul'},
    {name:'Beirut, Líbano', original:'Beirut'},
    {name:'Bishkek, Kirguistán', original:'Bishkek'},
    {name:'Brunéi', original:'Brunei'},
    {name:'Chitá, Rusia', original:'Chita'},
    {name:'Choibalsan, Mongolia', original:'Choibalsan'},
    {name:'Colombo, Sri Lanka', original:'Colombo'},
    {name:'Damascus, Siria', original:'Damascus'},
    {name:'Dhaka, Bangladés', original:'Dhaka'},
    {name:'Dili, Timor Oriental', original:'Dili'},
    {name:'Dubái, Emiratos Árabes Unidos', original:'Dubai'},
    {name:'Dusambé, Tayikistán', original:'Dushanbe'},
    {name:'Famagusta, Chipre', original:'Famagusta'},
    {name:'Gaza, Palestina', original:'Gaza'},
    {name:'Hebron, Palestina', original:'Hebron'},
    {name:'Ho Chi Minh, Vietnam', original:'Ho_Chi_Minh'},
    {name:'Hong Kong, China', original:'Hong_Kong'},
    {name:'Hovd, Mongolia', original:'Hovd'},
    {name:'Irkutsk, Rusia', original:'Irkutsk'},
    {name:'Jakarta, Indonesia', original:'Jakarta'},
    {name:'Jayapura, Indonesia', original:'Jayapura'},
    {name:'Jerusalem, Israel', original:'Jerusalem'},
    {name:'Kabul, Afganistán', original:'Kabul'},
    {name:'Kamchatka, Rusia', original:'Kamchatka'},
    {name:'Karachi, Pakistán', original:'Karachi'},
    {name:'Kathmandu, Nepal', original:'Kathmandu'},
    {name:'Khandyga, Rusia', original:'Khandyga'},
    {name:'Kolkata, India', original:'Kolkata'},
    {name:'Krasnoyarsk, Rusia', original:'Krasnoyarsk'},
    {name:'Kuala Lumpur, Malasia', original:'Kuala_Lumpur'},
    {name:'Kuching, Malasia', original:'Kuching'},
    {name:'Macau, China', original:'Macau'},
    {name:'Magadan, Rusia', original:'Magadan'},
    {name:'Makassar, Indonesia', original:'Makassar'},
    {name:'Manila, Filipinas', original:'Manila'},
    {name:'Nicosia, Chipre', original:'Nicosia'},
    {name:'Novokuznetsk, Rusia', original:'Novokuznetsk'},
    {name:'Novosibirsk, Rusia', original:'Novosibirsk'},
    {name:'Omsk, Rusia', original:'Omsk'},
    {name:'Oral, Kazajistán', original:'Oral'},
    {name:'Pontianak, Indonesia', original:'Pontianak'},
    {name:'Pyongyang, Corea del Norte', original:'Pyongyang'},
    {name:'Qatar', original:'Qatar'},
    {name:'Qostanay, Kazajistán', original:'Qostanay'},
    {name:'Kyzylorda, Kazajistán', original:'Qyzylorda'},
    {name:'Riyadh, Arabia Saudí', original:'Riyadh'},
    {name:'Sakhalin, Rusia', original:'Sakhalin'},
    {name:'Samarkand, Uzbekistán', original:'Samarkand'},
    {name:'Seoul, Corea del Sur', original:'Seoul'},
    {name:'Shanghai, China', original:'Shanghai'},
    {name:'Singapore', original:'Singapore'},
    {name:'Srednekolymsk, Rusia', original:'Srednekolymsk'},
    {name:'Taipei, Taiwán', original:'Taipei'},
    {name:'Tashkent, Uzbekistán', original:'Tashkent'},
    {name:'Tbilisi, Georgia', original:'Tbilisi'},
    {name:'Tehran, Irán', original:'Tehran'},
    {name:'Thimphu, Bután', original:'Thimphu'},
    {name:'Tokyo, Japón', original:'Tokyo'},
    {name:'Tomsk, Rusia', original:'Tomsk'},
    {name:'Ulaanbaatar, Mongolia', original:'Ulaanbaatar'},
    {name:'Urumqi, China', original:'Urumqi'},
    {name:'Ust-Nera, Rusia', original:'Ust-Nera'},
    {name:'Vladivostok, Rusia', original:'Vladivostok'},
    {name:'Yakutsk, Rusia', original:'Yakutsk'},
    {name:'Yangon, Birmania', original:'Yangon'},
    {name:'Yekaterinburg, Rusia', original:'Yekaterinburg'},
    {name:'Yerevan, Armenia', original:'Yerevan'}
  ],
  cities_atlantico: [
    {name:'Azores', original:'Azores'},
    {name:'Bermuda', original:'Bermuda'},
    {name:'Canary', original:'Canary'},
    {name:'Cape Verde', original:'Cape_Verde'},
    {name:'Faroe', original:'Faroe'},
    {name:'Madeira', original:'Madeira'},
    {name:'Reykjavik', original:'Reykjavik'},
    {name:'South Georgia', original:'South_Georgia'},
    {name:'Stanley', original:'Stanley'}
  ],
  cities_pacifico: [
    {name:'Apia', original:'Apia'},
    {name:'Auckland', original:'Auckland'},
    {name:'Bougainville', original:'Bougainville'},
    {name:'Chatham', original:'Chatham'},
    {name:'Chuuk', original:'Chuuk'},
    {name:'Easter', original:'Easter'},
    {name:'Efate', original:'Efate'},
    {name:'Enderbury', original:'Enderbury'},
    {name:'Fakaofo', original:'Fakaofo'},
    {name:'Fiji', original:'Fiji'},
    {name:'Funafuti', original:'Funafuti'},
    {name:'Galapagos', original:'Galapagos'},
    {name:'Gambier', original:'Gambier'},
    {name:'Guadalcanal', original:'Guadalcanal'},
    {name:'Guam', original:'Guam'},
    {name:'Honolulu', original:'Honolulu'},
    {name:'Kiritimati', original:'Kiritimati'},
    {name:'Kosrae', original:'Kosrae'},
    {name:'Kwajalein', original:'Kwajalein'},
    {name:'Majuro', original:'Majuro'},
    {name:'Marquesas', original:'Marquesas'},
    {name:'Nauru', original:'Nauru'},
    {name:'Niue', original:'Niue'},
    {name:'Norfolk', original:'Norfolk'},
    {name:'Noumea', original:'Noumea'},
    {name:'Pago Pago', original:'Pago_Pago'},
    {name:'Palau', original:'Palau'},
    {name:'Pitcairn', original:'Pitcairn'},
    {name:'Pohnpei', original:'Pohnpei'},
    {name:'Port Moresby', original:'Port_Moresby'},
    {name:'Rarotonga', original:'Rarotonga'},
    {name:'Tahiti', original:'Tahiti'},
    {name:'Tarawa', original:'Tarawa'},
    {name:'Tongatapu', original:'Tongatapu'},
    {name:'Wake', original:'Wake'},
    {name:'Wallis', original:'Wallis'}
  ],
  cities_australia: [
    {name:'Adelaide', original:'Adelaide'},
    {name:'Brisbane', original:'Brisbane'},
    {name:'Broken Hill', original:'Broken_Hill'},
    {name:'Currie', original:'Currie'},
    {name:'Darwin', original:'Darwin'},
    {name:'Eucla', original:'Eucla'},
    {name:'Hobart', original:'Hobart'},
    {name:'Lindeman', original:'Lindeman'},
    {name:'Lord Howe', original:'Lord_Howe'},
    {name:'Melbourne', original:'Melbourne'},
    {name:'Perth', original:'Perth'},
    {name:'Sydney', original:'Sydney'}
  ],
  hours: [
    {
      number: '00'
    },
    {
      number: '01'
    },
    {
      number: '02'
    },
    {
      number: '03'
    },
    {
      number: '04'
    },
    {
      number: '05'
    },
    {
      number: '06'
    },
    {
      number: '07'
    },
    {
      number: '08'
    },
    {
      number: '09'
    },
    {
      number: '10'
    },
    {
      number: '11'
    },
    {
      number: '12'
    },
    {
      number: '13'
    },
    {
      number: '14'
    },
    {
      number: '15'
    },
    {
      number: '16'
    },
    {
      number: '17'
    },
    {
      number: '18'
    },
    {
      number: '19'
    },
    {
      number: '20'
    },
    {
      number: '21'
    },
    {
      number: '22'
    },
    {
      number: '23'
    }
  ]
};
